### ISSUE TITLE
Recommend removing lodash to reduce package size

### ISSUE THREAD

**Issue by tohagan** [tom-s/speak-tts#10]
Thanks for your valued contribution with `speak-tts`.  Its just what I was looking for!

I'm coding a light weight app that needs to optimise load time. The `loadash` dependency adds significantly to this so wondering if we can replace some/all of these dependencies with something simpler that avoids an import. 

![image](https://user-images.githubusercontent.com/301525/52157370-4ee70600-26da-11e9-9739-7c08058e17b5.png)

**Comment by tohagan** [comment]
Sent you a PR for this.

**Comment by tom-s** [comment]
Thank you for raising this issue, https://github.com/tom-s/speak-tts/pull/12 should solve this.
