### ISSUE TITLE
Promises do not resolve consistently

### ISSUE THREAD

**Issue by kwcolson** [tom-s/speak-tts#14]
By using the demo website, I am unable to reliably have the speak 'onend' listener resolve.  After ~10 speakings, the Start Utterance will begin, without a corresponding End Utterance.  This also results in the speech.speaking() constantly reporting as true.

Attached image shows the demo website not resolving after 5 speaking attempts.

![image](https://user-images.githubusercontent.com/13997882/53256641-588ada80-3696-11e9-9481-8b15b02738bd.png)

**Comment by tom-s** [comment]
I can't reproduce the issue. What browser and what version are you using ? I know Chrome had some bugs with onEnd not firing on old versions.

**Comment by kwcolson** [comment]
thanks for the reply.  That must have been it.  When I went to check my
Chrome version it updated to the latest version and now....no problem!
Sorry for the wasted bandwidth.

-Ken

**Comment by tom-s** [comment]
No worries, I'm glad it's working for you !
