### ISSUE TITLE
Usage for ES5 

### ISSUE THREAD

**Issue by komms** [tom-s/speak-tts#16]
I have a few questions regarding the implementation of this module.
1) Is this module server based or client based? I think it is server based as it is using npm
2) Can it be used directly on client side javascript using browserify or other tool?
When I tried it to run on client side with es5 configuration it giving me an error
**Uncaught SyntaxError: Unexpected identifier** at  the line where I used   **var Speech = require('speak-tts')** 
 Can you please explain where I'm going wrong?

**Comment by tom-s** [comment]
1. It is client-based. It uses the browser speech API: https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis
2. Yes, that's what it's for
3. This has to do with your bundling/compiling. I suggest you start with a webpack boilerplate or something of that effect if that's something you don't know much about.
