### ISSUE TITLE
problem in Chrome

### ISSUE THREAD

**Issue by sarazaks** [tom-s/speak-tts#18]
There is a problem in Chrome in case there are some speakers on the screen (other browsers works fine)
If I have not finished yet playing one speaker, there is a problem when I'm going directly to the another speaker in the page
In other words, when you are play one speaker , you must perform two mouse clicks on other speaker  in order to start reading it. 
it doesn't give the first click to pass, I also see the problem in the demo: 
https://codesandbox.io/s/rmloxx60q4

**Comment by tom-s** [comment]
If you change the voice while an utterance is being played, it won't affect it. You need to change the voice and click play (create a new utterance). I believe this is by design in the browser text to speech API and doesn't seem like a bug to me ?

**Comment by tom-s** [comment]
Or perhaps I misunderstood the problem ?

**Comment by tom-s** [comment]
Closed due to inactivity
