### ISSUE TITLE
Huge delay (about 1 second) on Mac OSX 10.15 and Electron?

### ISSUE THREAD

**Issue by ogomez92** [tom-s/speak-tts#21]
Hello!
There seems to be a huge delay when running speak-tts on Electron using Catalina.
Has anyone else noticed it?
I'm making an app which requires high responsiveness in the tts library. How can I get in touch with you so that we can run further tests? Are you aware of this delay?

Thanks!

**Comment by tom-s** [comment]
Hi,
Perhaps you could try to using the raw speechSynthesis API (https://developer.mozilla.org/fr/docs/Web/API/SpeechSynthesis). If the issue remains, its something wrong with electron, if it doesn't it has to do with the library.

**Comment by tom-s** [comment]
@ogomez92: could you update me on your findings please ?

**Comment by ogomez92** [comment]
sadly it's a mac thing. It's not your library. Feel free to close the issue.

**Comment by tom-s** [comment]
Thanks for the update !
