### ISSUE TITLE
Why is it throwing ""An error occured while initializing : " Error in mobile when we open it for the first time in mobile 

### ISSUE THREAD

**Issue by Nayyaroddeen** [tom-s/speak-tts#27]
https://codesandbox.io/s/festive-fog-ljnjk?file=/src/index.js

Mobile Browser: Chrome

**Comment by Nayyaroddeen** [comment]
What is the fix for it?

**Comment by tom-s** [comment]
Could you remove the voice from the config (line 2), run it, and check in the select menu that the voice is actually available ?
On my mobile it's not whereas it is on my desktop. There is probably only one voice available on mobile anyway so you might as well just get rid of the voice param.

**Comment by tom-s** [comment]
I'm closing this issue.
