### ISSUE TITLE
How do I use plugin in Visual Studio?

### ISSUE THREAD

**Issue by pollaris** [tom-s/speak-tts#4]
How do I include this plugin in a cordova app in Visual Studio?

**Comment by pollaris** [comment]
The plugin failed to download from
https://github.com/tom-s/speak-tts.git
Please advise ...

**Comment by tom-s** [comment]
Im sorry I don't understand your question. This is not a visual studio plugin and the instructions are all in the readme: https://github.com/tom-s/speak-tts
