### ISSUE TITLE
giving "voice" parameter at init will result an error on speak

### ISSUE THREAD

**Issue by github0013** [tom-s/speak-tts#5]
## env

- "speak-tts": "^1.1.0",
- Chrome Version 65.0.3325.181 (Official Build) (64-bit)

## Problem

I just copied the readme example and ran it as below.

```js
Speech.init({
    'onVoicesLoaded': (data) => {console.log('voices', data.voices)},
    'lang': 'en-US', // specify en-US language (no detection applied)
    'volume': 0.5,
    'rate': 0.8,
    'pitch': 0.8,
    'voice': 'Samantha'
})

Speech.speak({text: "Samantha"})  // error ..
```

![](https://i.gyazo.com/2ca4da8210a5162efc1531574c7c8441.png)

![](https://i.gyazo.com/64c482d0ec0d1f0414b42bb36a346867.png)

![](https://i.gyazo.com/8483fd0288d643123a7812e96cf1ffd0.png)

## A workaround I found... (or maybe I am not fully understand the APIs)

Instead, if I don't give `voice` parameter but later set the voice works fine.

```js
Speech.init({
    'onVoicesLoaded': (data) => {console.log('voices', data.voices)},
    'lang': 'en-US', // specify en-US language (no detection applied)
    'volume': 0.5,
    'rate': 0.8,
    'pitch': 0.8
})

Speech.setVoice("Samantha")
Speech.speak({text: "Samantha"})
```

**Comment by tom-s** [comment]
Hi,

I have release a new version (2.0.3) which should solve the issue for you. Please note that the API has changed a bit and is now all promise-based.
