### ISSUE TITLE
onboundary not iterating

### ISSUE THREAD

**Issue by gsevla** [tom-s/speak-tts#9]
onboundary is doing nothing. 

Just for a test, I put a iterator inside it and in the end, the iterator kept the initial value.

`let clearText = this.cleanText(element);
        let words = clearText.split(' ');
        let index = 0;
        words.length

        this.speech.speak({
          text: clearText,
          queue: false, // current speech will be interrupted,
          listeners: {
              onstart: () => {
                  console.log("Start utterance");
                  element.innerHTML = element.innerHTML.replace(words[0], '<strong>' + words[0] + '</strong>');
                  index++;
              },
              onend: () => {
                  console.log("End utterance")
                  element.innerHTML = element.innerHTML.replace(words[words.length-1], '<strong>' + words[words.length-1] + '</strong>');
              },
              onresume: () => {
                  console.log("Resume utterance");
              },
              onboundary: (words) => {
                  console.log(words[index]);
                  //console.log(event.name + ' boundary reached after ' + event.elapsedTime + ' milliseconds.')
                  //console.log(words[index]);
                  //element.innerHTML = element.innerHTML.replace(words[index], '<strong>' + words[index] + '</strong>');
                  index++;
              }
          }
      }).then(() => {
          console.log(index);
          console.log(words[18-1]);
          console.log(words.length);
          console.log("Success !")
      }).catch(e => {
          console.error("An error occurred :", e)
      });`

element is a htmlelement and cleanText clean the htmlelement using regex.

**Comment by tom-s** [comment]
Hi @gsevla. Thanks for raising the issue but I don't think this issue is related to the library.
If you try this example that doesn't use speak-tts, the onboundary callback is not fired: https://codepen.io/anon/pen/mvmpjd?editors=1111
I believe this might be a chrome issue ?
